export const tweets = [
    {
        id: 0, 
        userName: 'Jake',
        handleName: 'awesomeJake',
        avatar: require(`./icons/kitty.jpg`),
        message: `I'm a big fan of cats. They're so cute!`,
        timeStamp: '2016-08-09 12:39:24',
        retweet: 27,
        like: 56,
    },
    {
        id: 1, 
        userName: 'Jessie',
        handleName: 'awesomeJessie',
        avatar: require(`./icons/panda.jpeg`),
        message: `I'm a big fan of pandas. They're so cute!`,
        timeStamp: '2018-03-23 21:19:42',
        retweet: 12,
        like: 9,
    },
    {
        id: 2, 
        userName: 'Cindy',
        handleName: 'awesomeCindy',
        avatar: require(`./icons/puppy.jpg`),
        message: `I'm a big fan of dogs. They're so cute!`,
        timeStamp: '2017-10-24 18:11:46',
        retweet: 18,
        like: 29,
    },
    {
        id: 3, 
        userName: 'Michael',
        handleName: 'awesomeMichael',
        avatar: require(`./icons/guinea-pig.png`),
        message: `I'm a big fan of guinea pigs. They're so cute!`,
        timeStamp: '2015-10-21 10:39:34',
        retweet: 62,
        like: 103,
    },
    {
        id: 4, 
        userName: 'Kate',
        handleName: 'awesomeKate',
        avatar: require(`./icons/hedgehog.jpeg`),
        message: `I'm a big fan of hedgehogs. They're so cute!`,
        timeStamp: '2017-10-02 22:09:40',
        retweet: 37,
        like: 42,
    },
]